// ═══════════════════════════════════════════
// LegalLens — jsPDF Report Generator
// ═══════════════════════════════════════════

window.exportPDFReport = function exportPDFReport({ docName, score, riskInfo, clauses, summary }) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = 210, pageH = 297, margin = 16;
  const contentW = pageW - margin * 2;
  let y = 0;

  const NAVY = [15, 35, 66];
  const MUTED = [100, 116, 139];
  const sevColor = { high: [220, 38, 38], medium: [217, 119, 6], info: [5, 150, 105] };
  const sevBg = { high: [254, 242, 242], medium: [255, 251, 235], info: [236, 253, 245] };

  function footer() {
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by LegalLens · Not a substitute for legal advice", pageW / 2, pageH - 8, { align: "center" });
  }

  function newPage() {
    footer();
    doc.addPage();
    y = margin;
  }

  function ensureSpace(needed) {
    if (y + needed > pageH - 20) newPage();
  }

  // ── PAGE 1: Header banner ──
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, pageW, 38, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.text("LegalLens", margin, 18);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(245, 158, 11);
  doc.text("AI LEGAL DOCUMENT RISK REPORT", margin, 26);
  doc.setTextColor(200, 210, 225);
  doc.setFontSize(9);
  doc.text("For Indian SMEs · Hindi & English", margin, 32);

  y = 50;

  // Document info
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Document Information", margin, y);
  y += 7;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.text(`File: ${docName}`, margin, y); y += 6;
  doc.text(`Analyzed on: ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`, margin, y); y += 6;
  if (summary) {
    doc.text(`Parties: ${summary.parties.join(" & ")}`, margin, y); y += 6;
    doc.text(`Contract Value: ${summary.amount}`, margin, y); y += 6;
    doc.text(`Jurisdiction: ${summary.jurisdiction}`, margin, y); y += 6;
  }
  y += 6;

  // Risk score block
  doc.setFillColor(...sevBg[riskInfo.riskLevel === "low" ? "info" : riskInfo.riskLevel]);
  doc.roundedRect(margin, y, contentW, 34, 3, 3, "F");
  const scoreColor = riskInfo.riskLevel === "high" ? sevColor.high : riskInfo.riskLevel === "medium" ? sevColor.medium : sevColor.info;
  doc.setTextColor(...scoreColor);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(30);
  const scoreWidth = doc.getTextWidth(`${score}`);
  doc.text(`${score}`, margin + 10, y + 17);
  doc.setFontSize(11);
  doc.setTextColor(...MUTED);
  doc.text("/ 100", margin + 10 + scoreWidth + 4, y + 17);
  doc.setTextColor(...scoreColor);
  doc.setFontSize(13);
  doc.text(riskInfo.label, margin + 10, y + 27);

  // Score bar
  const barX = margin + 80, barY = y + 14, barW = contentW - 95, barH = 5;
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(barX, barY, barW, barH, 2, 2, "F");
  doc.setFillColor(...scoreColor);
  doc.roundedRect(barX, barY, Math.max(4, barW * (score / 100)), barH, 2, 2, "F");
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text("0", barX, barY + 11);
  doc.text("100", barX + barW - 4, barY + 11);
  y += 44;

  // Counts
  const c = riskInfo.counts;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...sevColor.high);   doc.text(`${c.high} High Risk`, margin, y);
  doc.setTextColor(...sevColor.medium); doc.text(`${c.medium} Medium Risk`, margin + 45, y);
  doc.setTextColor(...sevColor.info);   doc.text(`${c.info} Standard / Info`, margin + 95, y);
  y += 10;

  // Summary
  if (summary) {
    doc.setTextColor(...NAVY);
    doc.setFontSize(13);
    doc.text("Plain Language Summary", margin, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(15, 23, 42);
    const lines = doc.splitTextToSize(summary.englishSummary, contentW);
    doc.text(lines, margin, y);
    y += lines.length * 5 + 8;
  }

  // ── PAGE 2+: Clauses ──
  newPage();
  doc.setTextColor(...NAVY);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Detected Clauses", margin, y);
  y += 9;

  const order = { high: 0, medium: 1, info: 2 };
  const sorted = [...clauses].sort((a, b) => order[a.severity] - order[b.severity]);

  sorted.forEach((cl, idx) => {
    const expl = doc.splitTextToSize(`What this means: ${cl.explanation}`, contentW - 8);
    const reco = doc.splitTextToSize(`What to do: ${cl.recommendation}`, contentW - 8);
    const snip = doc.splitTextToSize(`"${cl.snippetText.slice(0, 260)}${cl.snippetText.length > 260 ? "…" : ""}"`, contentW - 12);
    const blockH = 14 + snip.length * 4 + expl.length * 4.5 + reco.length * 4.5 + 14;
    ensureSpace(blockH);

    // Severity stripe + name
    doc.setFillColor(...sevColor[cl.severity]);
    doc.rect(margin, y - 4, 1.6, blockH - 6, "F");
    doc.setTextColor(...NAVY);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11.5);
    doc.text(`${idx + 1}. ${cl.name}`, margin + 5, y);
    // Badge
    const badge = cl.severity.toUpperCase();
    doc.setFontSize(8);
    doc.setTextColor(...sevColor[cl.severity]);
    doc.text(badge, pageW - margin - doc.getTextWidth(badge), y);
    y += 6;

    // Snippet
    doc.setFillColor(...sevBg[cl.severity]);
    doc.roundedRect(margin + 5, y - 3, contentW - 8, snip.length * 4 + 5, 2, 2, "F");
    doc.setFont("courier", "normal");
    doc.setFontSize(8);
    doc.setTextColor(71, 85, 105);
    doc.text(snip, margin + 8, y + 1.5);
    y += snip.length * 4 + 7;

    // Explanation
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(15, 23, 42);
    doc.text(expl, margin + 5, y);
    y += expl.length * 4.5 + 2;

    // Recommendation (bold)
    doc.setFont("helvetica", "bold");
    doc.text(reco, margin + 5, y);
    y += reco.length * 4.5 + 9;
  });

  footer();

  const base = (docName || "document").replace(/\.[^.]+$/, "").replace(/[^A-Za-z0-9_-]+/g, "_");
  doc.save(`LegalLens_Report_${base}.pdf`);
};
